# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.faith_cpp <- function(assay, rowTree) {
<<<<<<< HEAD
    .Call('_mia_faith_cpp', PACKAGE = 'mia', assay, rowTree)
=======
    .Call(`_mia_faith_cpp`, assay, rowTree)
}

.apply_transformation_difference_or_division <- function(mat, method = "difference") {
    .Call(`_mia_apply_transformation_difference_or_division`, mat, method)
>>>>>>> upstream/devel
}

